__author__ = 'kevin'

# Default colors, all colors available.
OFF = 0x0C
DIM_GREEN = 0x1C
MID_GREEN = 0x2C
GREEN = 0x3C

DIM_RED = 0x0D
DIM_AMBER = 0x1D
MID_YELLOWGREEN = 0x2D
YELLOWGREEN = 0x3D

MID_RED = 0x0E
MID_ORANGERED = 0x1E
MID_AMBER = 0x2E
YELLOW = 0x3E

RED = 0x0F
ORANGERED = 0x1F
ORANGE = 0x2F
AMBER = 0x3F


# Specific colors
RGB_RED_ACTIVE = RED
RGB_RED_INACTIVE = DIM_RED
RGB_GREEN_ACTIVE = GREEN
RGB_GREEN_INACTIVE = DIM_GREEN
RGB_BLUE_ACTIVE = AMBER
RGB_BLUE_INACTIVE = DIM_AMBER
RGB_WHITE_ACTIVE = YELLOW
RGB_WHITE_INACTIVE = MID_AMBER

LED_ON_STATE1 = YELLOW
LED_ON_STATE2 = YELLOWGREEN

LED_ON_ACTIVE = GREEN
LED_ON_INACTIVE = DIM_GREEN
LED_OFF_ACTIVE = RED
LED_OFF_INACTIVE = DIM_RED

STANDARD_ACTIVE = AMBER
STANDARD_INACTIVE = MID_AMBER
