__author__ = 'kevin'

# Default colors, all colors available.
OFF = "#000000"
DIM_GREEN = "#005500"
MID_GREEN = "#00aa00"
GREEN = "#00ff00"

DIM_RED = "#550000"
DIM_AMBER = "#554000"
MID_YELLOWGREEN = "#408000"
YELLOWGREEN = "#80ff00"

MID_RED = "#aa0000"
MID_ORANGERED = "#802000"
MID_AMBER = "#aa7f00"
YELLOW = "#ffff00"

RED = "#ff0000"
ORANGERED = "#ff4000"
ORANGE = "#ff7f00"
AMBER = "#ffbf00"

# Specific colors
RGB_RED_ACTIVE = RED
RGB_RED_INACTIVE = DIM_RED
RGB_GREEN_ACTIVE = GREEN
RGB_GREEN_INACTIVE = DIM_GREEN
RGB_BLUE_ACTIVE = AMBER
RGB_BLUE_INACTIVE = DIM_AMBER
RGB_WHITE_ACTIVE = YELLOW
RGB_WHITE_INACTIVE = MID_AMBER

LED_ON_STATE1 = YELLOW
LED_ON_STATE2 = YELLOWGREEN

LED_ON_ACTIVE = GREEN
LED_ON_INACTIVE = DIM_GREEN
LED_OFF_ACTIVE = RED
LED_OFF_INACTIVE = DIM_RED

STANDARD_ACTIVE = AMBER
STANDARD_INACTIVE = MID_AMBER